Document: foxchaser
Title: Debian foxchaser Manual
Author: <insert document author here>
Abstract: This manual describes what foxchaser is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/foxchaser/foxchaser.sgml.gz

Format: postscript
Files: /usr/share/doc/foxchaser/foxchaser.ps.gz

Format: text
Files: /usr/share/doc/foxchaser/foxchaser.text.gz

Format: HTML
Index: /usr/share/doc/foxchaser/html/index.html
Files: /usr/share/doc/foxchaser/html/*.html
